version: '2'

services:
  # server:
  #   build: .
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   links:
  #     - database
  #   command: [ 'yarn', 'dev' ]
  database:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ecommerce

volumes:
  database-data: {}
